name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: install dependencies
      run: |
        pip install -r requirements.txt
    # Build the book
    - name: build the book
      run: |
        jupyter-book build .
    # Push the book's HTML to github-pages
    - name: deploy book to GH pages branch
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        cname: mast30034.lfern.com
